version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.:/marblecutter
    volumes:
      - .:/opt/marblecutter/
      - /Users/michaelhiley/repos/marblecutter:/marblecutter
    ports:
      - "8000:8000"
    entrypoint: python
    command: server.py
